<?php

namespace AppBundle\Repository;

/**
 * listEmployeesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class listEmployeesRepository extends \Doctrine\ORM\EntityRepository
{
}
