<?php

namespace AppBundle\Repository;

/**
 * loginRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class login extends \Doctrine\ORM\EntityRepository
{
}
