test:
    resource: "@testBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

app_api:
    resource: "@AppBundle/Controller/api"
    type:     annotation
